### ISSUE TITLE
CLI refactor and enhanced support for newer revisions

### ISSUE THREAD

**Issue by ghost** [gdvalle/trafficserver_exporter#21]
Currently the CLI seems to be under-documented regarding the usage and options that are set by default and there seems to be lack of good defaults, hard requirement flags for required args like addr (setting this as localhost by default would be nice and this should possibly be a required argument)

I'd also like to refactor the CLI in such a way that least collectors are initialized, that is it starts up with the minimum functionality and the rest is offered as optional arguments to the end user.

Also add support for newer revisions of Python

I'd be happy to work and contribute to this if you happen to find this as a reasonable proposal.

Lastly thank you for working on this, the metrics seem to be really well organized by type.

**Comment by gdvalle** [comment]
I don't use this anymore, but I'm happy to assist if you'd like to make some improvements!

When you say refactor in such a way that the least collectors are initialized, are you referring to the `ProcessCollector`?  I think I chose the current default based on a standard install, and opted to just log a warning if we can't read the pidfile instead of erroring.  Optimistic, but not critical.

The `--addr` flag is empty by default which, if I recall, binds on all interfaces.  That one was chosen because I figured folks tend to run external Prometheus servers, so binding on localhost is not very useful.  I figure if you have public interfaces on the machine you'd hopefully be paying more attention to these arguments anyway.

I'd like to keep the project up-to-date with Python, so if you had any changes for that I'd be more than willing to accept PRs.

**Comment by ghost** [comment]
Yes, I was referring to the Process Collector, yes so having the --addr as localhost, makes it convenient for doing functional testing before exposing it on the public interface.
I'm also testing this with trafficserver9 and it works great so far.

**Comment by gdvalle** [comment]
Glad to hear v9 is working well!

I didn't mean to stall this discussion, but I'm not sure it's worth breaking for users that rely on the current `0.0.0.0` bind given it's easy to bind to localhost for dev work.

I went and added newer Python releases to the tox and setup.py suite in https://github.com/gdvalle/trafficserver_exporter/commit/5836d96841b6718713de5bf72d91ed6aaad0f5cd since this was opened, and also published it to [pypi](https://pypi.org/project/trafficserver-exporter/).

**Comment by ghost** [comment]
Yep makes sense, thank you for the changes, I'll close the PR for now and reopen in case required.
